-- 코드를 입력하세요
SELECT TO_CHAR(A.SALES_DATE,'YYYY-MM-DD') as SALES_DATE, A.PRODUCT_ID as PRODUCT_ID, A.USER_ID as USER_ID, A.SALES_AMOUNT as SALES_AMOUNT
FROM ONLINE_SALE A
WHERE A.SALES_DATE BETWEEN TO_DATE('2022-03-01' , 'YYYY-MM-DD') AND TO_DATE('2022-03-31' , 'YYYY-MM-DD')

UNION ALL

SELECT TO_CHAR(B.SALES_DATE,'YYYY-MM-DD') as SALES_DATE, B.PRODUCT_ID as PRODUCT_ID, NULL AS USER_ID , B.SALES_AMOUNT as SALES_AMOUNT
FROM OFFLINE_SALE B
WHERE B.SALES_DATE BETWEEN TO_DATE('2022-03-01' , 'YYYY-MM-DD') AND TO_DATE('2022-03-31' , 'YYYY-MM-DD')

ORDER BY SALES_DATE ASC, PRODUCT_ID ASC, USER_ID ASC;